FROM oven/bun:1.3-alpine AS production
WORKDIR /app

RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001

COPY --chown=nodejs:nodejs backend/dist ./backend/dist
COPY --chown=nodejs:nodejs backend/drizzle ./backend/drizzle
COPY --chown=nodejs:nodejs frontend/dist ./frontend/dist

ENV NODE_ENV=production
ENV PORT=3000
ENV MIGRATIONS_FOLDER=./backend/drizzle

EXPOSE 3000
USER nodejs
CMD ["bun", "./backend/dist/index.js"]
