import { randomInt } from "crypto";

const WORDS = [
  "ace", "air", "arc", "arm", "art", "ash", "axe", "bay", "bed", "bow",
  "box", "bud", "bug", "bus", "cap", "cat", "cog", "cow", "cup", "dam",
  "den", "dew", "dig", "dim", "dip", "dog", "dot", "dry", "dusk", "dust",
  "ear", "eel", "egg", "elk", "elm", "era", "eve", "eye", "fan", "far",
  "fen", "fig", "fin", "fir", "fly", "fog", "fox", "fur", "gem", "gill",
  "glow", "gnu", "gold", "gulf", "gust", "hawk", "hay", "helm", "herb",
  "hill", "hint", "hive", "hog", "hop", "horn", "hue", "hull", "hum",
  "ice", "imp", "ink", "inn", "ion", "iris", "isle", "ivy", "jar", "jaw",
  "jet", "joy", "jug", "keg", "kelp", "key", "kid", "kin", "kite", "knot",
  "lab", "lake", "lamb", "lamp", "lark", "lava", "leaf", "lens", "lime",
  "lion", "lip", "log", "loom", "lore", "lute", "lynx", "mane", "map",
  "mare", "marsh", "mast", "maze", "mesa", "mist", "mole", "moon", "moss",
  "moth", "mule", "musk", "nest", "newt", "nook", "oak", "oar", "orb",
  "orca", "ore", "otter", "owl", "pace", "palm", "path", "peak", "pear",
  "peat", "pine", "pit", "plain", "plum", "pod", "pond", "pool", "port",
  "prow", "puma", "quail", "quest", "rain", "ram", "ray", "reef", "reed",
  "rift", "rim", "riot", "rise", "roan", "rock", "root", "rose", "rove",
  "ruby", "rune", "rush", "rust", "sage", "sail", "salt", "sand", "sap",
  "seal", "seed", "shark", "shell", "shin", "shrub", "silk", "silt", "sky",
  "slab", "slag", "slate", "sleet", "slope", "sloth", "smoke", "snail",
  "snap", "snow", "soil", "sole", "span", "spark", "spire", "spore", "spot",
  "spring", "sprout", "stag", "star", "stem", "step", "stone", "storm",
  "stream", "stump", "sun", "surge", "swan", "swift", "thorn", "tide",
  "tiger", "timber", "toad", "torch", "trail", "trout", "tuft", "tusk",
  "vale", "vine", "vole", "wade", "wake", "wave", "weed", "well", "whelk",
  "wind", "wing", "wolf", "wood", "wren", "yak", "yarn", "yew", "zinc",
  "zone", "bloom", "brave", "bright", "brook", "calm", "cedar", "cliff",
  "cloud", "coast", "crest", "crisp", "crop", "crown", "crystal", "dale",
  "dawn", "deep", "delta", "dense", "dune", "falls", "fern", "field",
  "fjord", "flame", "fleet", "flock", "flora", "flume", "forge", "forest",
  "frost", "gale", "glade", "glen", "gorge", "grass", "grove", "gull",
  "heron", "hollow", "jade", "jasper", "juniper", "keen", "knoll", "lagoon",
  "loch", "lodge", "lunar", "mallow", "maple", "meadow", "mesa", "moor",
  "moose", "mount", "murk", "noble", "north", "pasture", "pebble", "pillar",
  "pine", "pivot", "plain", "plover", "plume", "polar", "pollen", "prism",
  "rapid", "raven", "ridge", "river", "robin", "rocky", "roost", "ruddy",
  "shale", "shore", "sierra", "silver", "slate", "solstice", "south", "sparrow",
  "spruce", "stark", "steep", "stone", "stork", "sunset", "surf", "swamp",
  "talon", "tangle", "talon", "thatch", "thistle", "timber", "torrent",
  "tower", "tundra", "valley", "verdant", "vernal", "vista", "vivid",
  "warbler", "warren", "wasatch", "watch", "water", "wattle", "west",
  "wetland", "wheat", "white", "willow", "wisp", "zenith",
];

export function generatePassphrase(): string {
  return [0, 1, 2, 3].map(() => WORDS[randomInt(WORDS.length)]).join("-");
}
